spring:
  application:
    name: ragcraft

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  ai:
    vertex:
      ai:
        embedding:
          project-id: "rag-craft"
          location: "us-central1"
          text:
            options:
              model: gemini-embedding-001
              dimensions: 3072
        gemini:
          project-id: rag-craft
          location: us-central1
          chat:
            options:
              model: gemini-2.0-flash   # 예시 (원하면 pro로 변경)
app:
  s3:
    bucket: ragcraft-source-bucket

elasticsearch:
  host: ${ES_HOST}
  apiKey: ${ES_API_KEY}