spring:
  application:
    name: ragcraft

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  ai:
    vertex:
      ai:
        embedding:
          project-id: "rag-craft"
          location: "us-central1"
          model: "gemini-embedding-001"

app:
  s3:
    bucket: ragcraft-source-bucket